# Generated by Django 3.2.11 on 2022-04-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=255, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Empregado',
                'verbose_name_plural': 'Empregados',
                'ordering': ['id'],
            },
        ),
    ]
